export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const ADD_SERVICE_REQUEST    = 'ADD_SERVICE_REQUEST';
export const ADD_SERVICE_FAILURE    = 'ADD_SERVICE_FAILURE';
export const ADD_SERVICE_SUCCESS    = 'ADD_SERVICE_SUCCESS';
export const REMOVE_SERVICE         = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD   = 'CHANGE_SERVICE_FIELD';

// edit
export const EDIT_SERVICE_REQUEST    = 'EDIT_SERVICE_REQUEST';
export const EDIT_SERVICE_FAILURE    = 'EDIT_SERVICE_FAILURE';
export const EDIT_SERVICE_SUCCESS    = 'EDIT_SERVICE_SUCCESS';
export const GET_SERVICE_SUCCESS     = 'GET_SERVICE_SUCCESS';
